<h1>Update Client</h1>
<?php
include 'dbh.php';
$_SESSION['message']='';
$sql="SELECT * FROM cstat";
$fetch= mysqli_query($conn, $sql);
?>
<?php
 if (is_array($row)):?>
<form action="?page=Client_Manager&action=doUpdate" method="post">
Company name:<input type="text" name="c_name" value="<?php echo $row[1];?>"><br>
Business number:<input type="text" name="b_num" value="<?php echo $row[2];?>"><br>
Contact’s first name:<input type="text" name="f_name" value="<?php echo $row[3];?>"><br>
Contact’s last name:<input type="text" name="l_name" value="<?php echo $row[4];?>"><br>
Phone number:<input type="text" name="p_num" value="<?php echo $row[5];?>"><br>
Cell number:<input type="text" name="c_num" value="<?php echo $row[6];?>"><br>
Website:<input type="text" name="w_site" value="<?php echo $row[7];?>"><br>
Status:<select name="stat">
        <option value="">Choose...</option>
        <?php
        while ($rowsta= mysqli_fetch_array($fetch)) {
        echo '<option value="'.$rowsta['cstatid'].'">'.$rowsta['cstatus'].'</option>';
        }
        ?>
       </select><br>
<input type="hidden" name="id" value="<?php echo $row[0];?>">
<input type="submit">
</form>
<?php else:?>
<h1>No Client Found</h1>
<?php endif;?>
<?php
//echo "<a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank' class='viewsource' style='color:#a3d0f0;'>view source</a>";
?>