<?php

include 'dbh.php';
?>
<h1>View Client</h1>
<style>
div.scrollmenu {
    width: auto; 
    height: 350px;
    overflow: auto;
    white-space: nowrap;
}
</style>
<div class="scrollmenu">
<table>
<thead>	
    <tr>
            <th>Company</th>
            <th>Business Number</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone</th>
            <th>Cell</th>
            <th>website</th>
            <th>Status</th>
            <th>Edit</th>
    </tr>
</thead>
<tbody>
	<?php
        $sql="SELECT * FROM client";
	$query = mysqli_query($conn,$sql);
	while($row = mysqli_fetch_array($query)){
         if($row['status']==1){
             $row['status']="Active";
         } else {
             $row['status']="Archive";             
         }   
echo 	'<tr id="'.$row['cid'].'">
        <td>'.$row['company'].'</td>
        <td>'.$row['bnumber'].'</td>
        <td>'.$row['fname'].'</td>
        <td>'.$row['lname'].'</td>
        <td>'.$row['phone'].'</td>
        <td>'.$row['cell'].'</td>
        <td>'.$row['website'].'</td>
        <td>'.$row['status'].'</td>
        <td><a href="?page=Client_Manager&action=update&id='.$row['cid'].'">Edit</td>
        </tr>';				
	}
	?>
</tbody>
</table>
</div>
  
<?php 

?>
<?php
//echo "<a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank' class='viewsource' style='color:#a3d0f0;'>view source</a>";
?>