<?php 

include 'dbh.php';
?>
<h1>View Users</h1>
<style>
div.scrollmenu {
    width: 650px; 
    height: 350px;
    overflow: auto;
    white-space: nowrap;
}

</style>
<div class="scrollmenu">
<table>
<thead>	
    <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Cell</th>
            <th>Position</th>
            <th>User Name</th>
            <th>Password</th>
            <th>Status</th>
            <th>Image</th>
            <th>Edit</th>
    </tr>
</thead>
    <tbody>
     	<?php
        $sql="SELECT * FROM users";
	$query = mysqli_query($conn,$sql);
	while($row = mysqli_fetch_array($query)){
        
        $userposrecord=$row['position'];
        $pos="SELECT pname FROM position WHERE pid =$userposrecord";
        $posquery=mysqli_query($conn,$pos);
        $rowcpo=mysqli_fetch_array($posquery);
            if ($row['position']>0) {
                $row['position']=($rowcpo['pname']);
            }
        $userstatrecord=$row['ustatus'];
        $ustat="SELECT ustatname FROM ustatus WHERE ustatid =$userstatrecord";
        $statquery=mysqli_query($conn,$ustat);
        $rowstatus=mysqli_fetch_array($statquery);
        if ($row['ustatus']>0) {
           $row['ustatus']=($rowstatus['ustatname']); 
        }
echo 	'<tr id="'.$row['uid'].'">
        <td>'.$row['fname'].'</td>
        <td>'.$row['lname'].'</td>
        <td>'.$row['email'].'</td>
        <td>'.$row['cellnumber'].'</td>
        <td>'.$row['position'].'</td>            
        <td>'.$row['username'].'</td>
        <td>'.$row['password'].'</td>
        <td>'.$row['ustatus'].'</td>
        <td><img src='.$row['image'].' class="upic"></td>
        <td><a href="?page=User_Manager&action=update&id='.$row['uid'].'">Edit</td>
        </tr>';				
	}
	?>   
    </tbody>
    </table>
    </div>

<?php
//echo "<a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank' class='viewsource' style='color:#a3d0f0;'>view source</a>";
?>